# Generated by Django 4.1.7 on 2023-04-04 06:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_app', '0005_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyPost',
            fields=[
                ('vacancy_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('employment_type', models.CharField(blank=True, max_length=255)),
                ('shift', models.CharField(blank=True, max_length=255)),
                ('skills', models.CharField(blank=True, max_length=255)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('address_coordinates', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('description', models.TextField(blank=True)),
                ('applicants', models.ManyToManyField(blank=True, related_name='vacancy_post', to='account_app.intern')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_post', to='account_app.recruiter')),
            ],
        ),
        migrations.CreateModel(
            name='VacancyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=255)),
                ('note', models.TextField(blank=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_application', to='account_app.intern')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_application', to='vacancies.vacancypost')),
            ],
        ),
    ]
