# Generated by Django 4.1.7 on 2023-04-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_alter_vacancyapplication_id_alter_vacancypost_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancypost',
            name='salary',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
