# Generated by Django 4.1.7 on 2023-04-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_remove_vacancyapplication_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancypost',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
