# Generated by Django 4.1.7 on 2023-04-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_alter_vacancypost_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancypost',
            name='salary',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
