# Generated by Django 4.1.7 on 2023-05-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_alter_vacancypost_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancypost',
            name='education_level',
            field=models.CharField(choices=[('High School', 'High School'), ('Diploma', 'Diploma'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Doctorate', 'Doctorate')], default='Bachelor', max_length=20),
        ),
    ]
