# Generated by Django 4.1.7 on 2023-03-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('recruiter', 'Recruiter'), ('intern', 'Intern')], default='intern', max_length=10),
        ),
    ]
