# Generated by Django 4.1.7 on 2023-04-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_customuser_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='phone_number',
            field=models.CharField(default='123456789123', max_length=15),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='company_name',
            field=models.CharField(default='Company Name', max_length=100),
        ),
    ]
