# Generated by Django 4.1.7 on 2023-04-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='position',
            field=models.CharField(choices=[('Intern', 'Intern'), ('Junior', 'Junior'), ('Middle', 'Middle'), ('Senior', 'Senior'), ('Lead', 'Lead'), ('Manager', 'Manager'), ('Director', 'Director'), ('Vice President', 'Vice President'), ('Senior Vice President', 'Senior Vice President'), ('Executive Vice_president', 'Executive Vice President'), ('Chief Officer', 'Chief Officer'), ('President', 'President')], default='Intern', max_length=255),
        ),
    ]
