# Generated by Django 4.1.7 on 2023-04-02 13:42

import account_app.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0004_alter_customuser_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='company_name',
            field=models.CharField(default='Company Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, validators=[account_app.validations.validate_location]),
        ),
    ]
