# Generated by Django 4.1.7 on 2023-04-24 20:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0004_alter_workexperience_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
