# Generated by Django 4.1.7 on 2023-04-24 20:40

import account_app.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0005_alter_award_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='img_profile',
            field=models.ImageField(blank=True, upload_to='profile_img/', validators=[account_app.validations.validate_profile]),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logo/', validators=[account_app.validations.validate_profile]),
        ),
    ]
